module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      "collapse",
      "collapsed",
      "collapsing",
      "show",
      "dropdown-menu",
      "dropdown-item",
      "dropdown-divider",
      "sr-only",
      "table",
      "table-dark",
      "table-hover",
      "table-responsive",
      "af-tooltip",
      "af-popover",
      "font-weight-bold",
      "font-weight-medium",
      "font-weight-lighter",
      "scrolled",
      "active",
      "fixed-top",
      "fixed-top-nav",
      "sticky-top",
      "row",
      "bullet",
    ],
    deep: [
      /^navbar/,
      /^nav-/,
      /^post-/,
      /^card/,
      /^profile/,
      /^publications/,
      /^projects/,
      /^news/,
      /^tag-/,
      /^toggle/,
      /^search/,
      /^footer/,
      /^btn/,
      /data-theme/,
      /^fixed-/,
      /^sticky-/,
      /^row/,
      /^col-/,
      /^pagination/,
      /^page-/,
      /^icon-bar/,
      /^dropdown/,
      /^sr-/,
    ],
    greedy: [/modal/, /tooltip/, /popover/],
  },
};
